### ISSUE TITLE
Error when update to Symfony 2.4.1

### ISSUE THREAD

**Issue by KhanMaytok** [hasinhayder/openshift-symfony-2.3.0#1]
Hi.
I get an error when I try update to Symfony 2.4.1. I copied the line "symfony/symfony": "~2.4", and I pasted to the original composer.json. But when i pushed to my openshift repo, I get this error:

remote:     - The requested package symfony/symfony could not be found in any version, there may be
a typo in the package name.
remote:
remote: Potential causes:
remote:  - A typo in the package name
remote:  - The package is not available in a stable-enough version according to your minimum-stabili
ty setting
remote:    see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more deta
ils.
remote:
remote: Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.
remote: PHP Warning:  require_once(/var/lib/openshift/52df07ea50044625e1000247/app-root/runtime/repo
/php/app/bootstrap.php.cache): failed to open stream: No such file or directory in /var/lib/openshif
t/52df07ea50044625e1000247/app-root/runtime/repo/php/app/console on line 10
remote: PHP Stack trace:
remote: PHP   1. {main}() /var/lib/openshift/52df07ea50044625e1000247/app-root/runtime/repo/php/app/
console:0
remote: PHP Fatal error:  require_once(): Failed opening required '/var/lib/openshift/52df07ea500446
25e1000247/app-root/runtime/repo/php/app/bootstrap.php.cache' (include_path='.:/usr/share/pear:/usr/
share/php') in /var/lib/openshift/52df07ea50044625e1000247/app-root/runtime/repo/php/app/console on
line 10
remote: PHP Stack trace:
remote: PHP   1. {main}() /var/lib/openshift/52df07ea50044625e1000247/app-root/runtime/repo/php/app/
console:0

Can you help me?

**Comment by xmontana** [comment]
The problem is the ICU library http://symfony.com/doc/current/components/intl.html#installation

Add to your composer.json:

```
 "symfony/icu": "1.0.*",
```

and update your composer.lock file symfony/icu

```
php composer.phar update 
```

then commit and push to deploy

 Note: your composer.json should look like these:

```
 "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "~2.4",
        "symfony/icu": "1.0.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~2.3",
        "sensio/framework-extra-bundle": "~3.0",
        "sensio/generator-bundle": "~2.3",
        "incenteev/composer-parameter-handler": "~2.0"
    },
```

**Comment by xmontana** [comment]
If your cartridge is PHP 5.4, you can use 
´´´
 "symfony/icu": "1.1.*",
´´´
(remember to update your composer dependencies.
